#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 25 06:50:25 2019

@author: chansa
"""

class stack:
    
    def _init_(self):
        self.items = []
    
    
    def push(self, item):
        self.items.append(item)
    
    def pop(self):
        pass
    
    def peek(self):
        pass
    
    def size(self):
        pass
        
    
    def is_empty(self):
        pass
    
#add some comments